### ISSUE TITLE
Modal-View

### ISSUE THREAD

**Issue by Lohit9** [Lohit9/React-Native-Sample-#1]
The Product view is not displaying modally

**Comment by nevace** [comment]
Hey @Lohit9, I was looking at the Shopify Mobile SDK for an iOS app and since I code primarily in Javascript, googled for a React Native solution. I can see that the Shopify GitHub had something on there but it's been removed. What are you plans for this repo?

**Comment by Lohit9** [comment]
@nevace  Hi, This repo is outdated and I am not working on it right now. Can you please post an issue in the Shopify Mobile SDK iOS repo: https://github.com/Shopify/mobile-buy-sdk-ios 

And also could you ping me with the link to the issue after you post it. thanks

**Comment by nevace** [comment]
It's not an issue, I'm confused how you used React  Native in your sample app when there's no mention of it on the Shopify repo.

**Comment by Lohit9** [comment]
Yes, we are working on the React Native sample app using the Mobile Buy SDK. It should be available to sometime next week.

**Comment by nevace** [comment]
Ok cool, I'll keep a look out for it.

**Comment by Lohit9** [comment]
@nevace you can find the react native sample apps for Shopify's Mobile Buy SDK here: https://github.com/Lohit9/mobile-buy-sdk-react-native-sample
Sorry for the delay

**Comment by nevace** [comment]
Cool, this looks good. I haven't got api details to hand so haven't installed it yet but should do tomorrow. Did you create a React Native module from the Mobile Buy SDK then?
